language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
matrix:
  allow_failures:
    # Allow python development branches to fail
    # it could be outside of my control
    - python: "3.9-dev"
    - python: "nightly"
# command to install dependencies
install:
  - pip install ".[dev]"
# command to run tests
script:
  - pytest --cov-report=xml --cov solver
# submit coverage
after_success:
  - codecov