[tool.black]
line-length = 79
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.vscode
    | \.mypy_cache
    | \env
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''